# Generated by Django 2.0 on 2020-10-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_auto_20201003_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconform',
            name='role',
        ),
    ]
