# Generated by Django 2.0 on 2020-10-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_remove_emailconform_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconform',
            name='role',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
