# Generated by Django 2.0 on 2020-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_emailconform_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailnotconform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(default='none', max_length=50)),
            ],
        ),
    ]
