# Generated by Django 2.0 on 2020-10-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_auto_20201003_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconform',
            name='address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='emailconform',
            name='phone',
            field=models.CharField(default='00', max_length=12),
        ),
    ]
