# Generated by Django 2.0 on 2020-10-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_auto_20201003_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emailconform',
            name='phone',
        ),
    ]
